### ISSUE TITLE
Leaflet default marker changes style on edit

### ISSUE THREAD

**Issue by JeroenDeDauw** [dwilhelm89/Leaflet.StyleEditor#87]
Using master (8054a4ff462ef0126582a3789e5c7688aa2e18ab)

![ezgif-3-bedf882d4ef5](https://user-images.githubusercontent.com/146040/69287791-cea57900-0bf7-11ea-98fe-3bcf2360ee77.gif)

When I enter edit mode, the marker changes. There appears to be no way to get back to the default. Closing edit mode does not restore the marker.

Is there a way to fully disable marker icon editing? I do not need this feature at present.

**Comment by fupduck** [comment]
Sadly this is currently not possible.
But sure makes sense to add this feature.
I guess the simplest way would be not to react if the corresponding form is disabled/empty

**Comment by fupduck** [comment]
Please have a look @ https://github.com/dwilhelm89/Leaflet.StyleEditor/pull/91

This adds the `ignoreLayerTypes` option which gets an array of layer types to ignore.
Layer types in this case are "Marker", "Polyline", "Polygon" and "Rectangle".

I introduced these strings so it is possible to disable "Polyline" without disabling "Polygon" as well because of inheritance.

Do you think the name makes sense for this option?

**Comment by JeroenDeDauw** [comment]
I gave up on using this editor for now because of the icon issue. If with this new option makes the editor ignore markers altogether, then I'd be able to use it for other layer types.

I had a quick look at your code change. Not seeing anything wrong, but then again I don't know this codebase.

**Comment by fupduck** [comment]
Closed by https://github.com/dwilhelm89/Leaflet.StyleEditor/releases/tag/v0.1.15
